version: '3.8'

services:

  # api_manager:
  #     image: wso2/wso2am:4.0.0
  #     container_name: api_manager
  #     ports:
  #       - "8280:8280"
  #       - "8243:8243"
  #       - "9443:9443"
  #     volumes:
  #       - aa:/home/wso2carbon/wso2am-4.0.0/repository/*

  # kafka:
  #     image: docker.io/bitnami/kafka:3.4
  #     ports:
  #       - "9092:9092"
     
  #     environment:
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092




  # routerapp:
  #   container_name: routerApp
  #   build:
  #     context: .
  #   # command: tail -F anything
  #   ports:
  #     - '8000:80'
  #   environment:
  #     - KAFKA_HOST=kafka:9092

  #   depends_on:
  #     - kafka
  #     - zookeeper
  #     - db

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  aa:
